baseurl: ""

repo: "https://github.com/TristanD2004/TristanD2004.github.io"
github_user: "TristanD2004"
github_repo: "TristanD2004.github.io"



collections:
    projects:
        output: true

defaults:
    - scope:
          path: "_projects"
      values:
          banner: "/assets/images/lamp-project.jpg"
          excerpt_separator: "<!--more-->"
          layout: "project"
    - scope:
          path: "_posts"
      values:
          banner: "/assets/images/blog.jpg"
          excerpt_separator: "<!--more-->"
          layout: "blogpost"
    - scope:
          path: ""
      values:
          layout: "mainpage"

exclude:
    - "*.script.md"